package llm

import (
	"strings"
	"testing"

	"docgen/internal/config"
)

func TestMockRouterGenerate(t *testing.T) {
	router := NewRouter(config.Config{LLMProvider: "mock"})
	got, err := router.Generate("system", "user")
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if !strings.Contains(got, "Generated by the Go mock provider.") {
		t.Fatalf("unexpected mock output: %q", got)
	}
}

func TestUnsupportedProviderReturnsError(t *testing.T) {
	router := NewRouter(config.Config{LLMProvider: "does-not-exist"})
	if _, err := router.Generate("system", "user"); err == nil {
		t.Fatal("expected error for unsupported provider")
	}
}
