package llm

import (
	"errors"
	"fmt"
	"strings"

	"docgen/internal/config"
)

type Router struct {
	provider string
	client   Client
}

func NewRouter(cfg config.Config) *Router {
	provider := strings.ToLower(cfg.LLMProvider)
	return &Router{
		provider: provider,
		client:   newClient(provider, cfg),
	}
}

func (r *Router) Generate(systemPrompt, userPrompt string) (string, error) {
	if r.client == nil {
		return "", fmt.Errorf("unsupported llm provider %q", r.provider)
	}
	return r.client.Generate(systemPrompt, userPrompt)
}

func newClient(provider string, cfg config.Config) Client {
	switch provider {
	case "", "mock":
		return MockClient{Provider: "mock"}
	case "openai":
		return NewOpenAIClient(cfg.OpenAIBaseURL, cfg.OpenAIAPIKey, cfg.OpenAIModel, "", "")
	case "openrouter":
		return NewOpenAIClient(cfg.OpenAIBaseURL, cfg.OpenAIAPIKey, cfg.OpenAIModel, "https://openrouter.ai", "docgen")
	case "deepseek", "custom":
		return NewOpenAIClient(cfg.OpenAIBaseURL, cfg.OpenAIAPIKey, cfg.OpenAIModel, "", "")
	case "ollama":
		return NewOllamaClient(cfg.OpenAIBaseURL, cfg.OpenAIModel)
	default:
		return nil
	}
}

type MockClient struct {
	Provider string
}

func (c MockClient) Generate(systemPrompt, userPrompt string) (string, error) {
	if strings.TrimSpace(userPrompt) == "" {
		return "", errors.New("user prompt is required")
	}
	return fmt.Sprintf("%s\n\n%s\n\nGenerated by the Go %s provider.", systemPrompt, userPrompt, c.Provider), nil
}
