package llm

import (
	"strings"
	"testing"

	"xpert/internal/config"
)

func TestMockRouterGenerate(t *testing.T) {
	router := NewRouter(config.Config{LLMProvider: "mock", OpenAIModel: "test-model"})
	got, err := router.Generate("system", "user")
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if !strings.Contains(got, "Generated by the Go mock provider") {
		t.Fatalf("unexpected mock output: %q", got)
	}
}

func TestUnsupportedProviderReturnsError(t *testing.T) {
	router := NewRouter(config.Config{LLMProvider: "does-not-exist"})
	if _, err := router.Generate("system", "user"); err == nil {
		t.Fatal("expected error for unsupported provider")
	}
}

func TestRouterWithModelPool(t *testing.T) {
	cfg := config.Config{
		LLMProvider:                "mock",
		OpenAIModel:                "default-model",
		AIModelPool:                []string{"model-a", "model-b", "model-c"},
		EnableRandomModelSelection: true,
	}

	router := NewRouter(cfg)

	// Generate multiple times and verify different models are selected
	selectedModels := make(map[string]bool)
	for i := 0; i < 30; i++ {
		result, err := router.GenerateWithMetadata("system", "user")
		if err != nil {
			t.Fatalf("Generate returned error: %v", err)
		}
		selectedModels[result.ModelUsed] = true
	}

	// With random selection over 30 tries, we should see at least 2 different models
	if len(selectedModels) < 2 {
		t.Errorf("Expected multiple models to be selected, got %d unique models", len(selectedModels))
	}

	// Verify only pool models are selected, not default
	if selectedModels["default-model"] {
		t.Error("Default model should not be selected when pool is enabled")
	}
}

func TestRouterBackwardCompatibility(t *testing.T) {
	// Feature flag disabled - should use single model
	cfg := config.Config{
		LLMProvider:                "mock",
		OpenAIModel:                "gpt-4o-mini",
		AIModelPool:                []string{"model-a", "model-b"},
		EnableRandomModelSelection: false, // Disabled
	}

	router := NewRouter(cfg)
	result, err := router.GenerateWithMetadata("system", "user")
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	if result.ModelUsed != "gpt-4o-mini" {
		t.Errorf("Expected default model 'gpt-4o-mini', got %s", result.ModelUsed)
	}
}

func TestRouterGenerateWithMetadata(t *testing.T) {
	cfg := config.Config{
		LLMProvider:                "mock",
		OpenAIModel:                "test-model",
		EnableRandomModelSelection: false,
	}

	router := NewRouter(cfg)
	result, err := router.GenerateWithMetadata("system prompt", "user prompt")
	if err != nil {
		t.Fatalf("GenerateWithMetadata returned error: %v", err)
	}

	if result.Content == "" {
		t.Error("Expected non-empty content")
	}
	if result.ModelUsed != "test-model" {
		t.Errorf("Expected model 'test-model', got %s", result.ModelUsed)
	}
	if result.Attempts != 1 {
		t.Errorf("Expected 1 attempt, got %d", result.Attempts)
	}
	if len(result.FailedModels) != 0 {
		t.Errorf("Expected no failed models, got %v", result.FailedModels)
	}
}

func TestRouterGetAvailableModels(t *testing.T) {
	tests := []struct {
		name     string
		cfg      config.Config
		expected []string
	}{
		{
			name: "single model when disabled",
			cfg: config.Config{
				OpenAIModel:                "gpt-4o",
				EnableRandomModelSelection: false,
			},
			expected: []string{"gpt-4o"},
		},
		{
			name: "pool models when enabled",
			cfg: config.Config{
				OpenAIModel:                "default",
				AIModelPool:                []string{"model-a", "model-b"},
				EnableRandomModelSelection: true,
			},
			expected: []string{"model-a", "model-b"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			router := NewRouter(tt.cfg)
			models := router.GetAvailableModels()
			if len(models) != len(tt.expected) {
				t.Errorf("Expected %d models, got %d", len(tt.expected), len(models))
			}
		})
	}
}

func TestRouterEmptyPoolWithFeatureEnabled(t *testing.T) {
	// Edge case: feature enabled but empty pool should fall back to default
	cfg := config.Config{
		LLMProvider:                "mock",
		OpenAIModel:                "fallback-model",
		AIModelPool:                nil,
		EnableRandomModelSelection: true,
	}

	router := NewRouter(cfg)
	result, err := router.GenerateWithMetadata("system", "user")
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	if result.ModelUsed != "fallback-model" {
		t.Errorf("Expected fallback to default model, got %s", result.ModelUsed)
	}
}
