package llm

import (
	"errors"
	"fmt"
	"log"
	"strings"

	"xpert/internal/config"
)

// GenerateResult contains the response and metadata.
type GenerateResult struct {
	Content      string
	ModelUsed    string
	Attempts     int
	FailedModels []string
}

// Router routes LLM requests to the appropriate client with model selection.
type Router struct {
	provider   string
	selector   *ModelSelector
	factory    *ClientFactory
	maxRetries int
}

// NewRouter creates a new Router with model pool support.
func NewRouter(cfg config.Config) *Router {
	var pool []string
	if cfg.EnableRandomModelSelection && len(cfg.AIModelPool) > 0 {
		pool = cfg.AIModelPool
	}

	maxRetries := len(pool)
	if maxRetries < 1 {
		maxRetries = 1
	}

	return &Router{
		provider:   strings.ToLower(cfg.LLMProvider),
		selector:   NewModelSelector(cfg.OpenAIModel, pool, cfg.EnableRandomModelSelection),
		factory:    NewClientFactory(cfg),
		maxRetries: maxRetries,
	}
}

// Generate performs LLM generation with automatic fallback.
// This method maintains backward compatibility with the original signature.
func (r *Router) Generate(systemPrompt, userPrompt string) (string, error) {
	result, err := r.GenerateWithMetadata(systemPrompt, userPrompt)
	if err != nil {
		return "", err
	}
	return result.Content, nil
}

// GenerateWithMetadata performs generation and returns full metadata.
func (r *Router) GenerateWithMetadata(systemPrompt, userPrompt string) (*GenerateResult, error) {
	failedModels := make(map[string]bool)
	var lastErr error
	attempts := 0

	maxAttempts := r.maxRetries
	if maxAttempts < 1 {
		maxAttempts = 1
	}

	for attempts < maxAttempts {
		attempts++

		var model string
		var err error

		if attempts == 1 {
			model = r.selector.Select()
		} else {
			model, err = r.selector.SelectExcluding(failedModels)
			if err != nil {
				log.Printf("[llm] no more models available for fallback: %v", err)
				break
			}
			log.Printf("[llm] attempting fallback with model: %s (attempt %d)", model, attempts)
		}

		client := r.factory.CreateClient(model)
		if client == nil {
			return nil, fmt.Errorf("unsupported llm provider %q", r.provider)
		}

		content, err := client.Generate(systemPrompt, userPrompt)
		if err != nil {
			log.Printf("[llm] model %s failed: %v", model, err)
			failedModels[model] = true
			lastErr = err
			continue
		}

		failedList := make([]string, 0, len(failedModels))
		for m := range failedModels {
			failedList = append(failedList, m)
		}

		return &GenerateResult{
			Content:      content,
			ModelUsed:    model,
			Attempts:     attempts,
			FailedModels: failedList,
		}, nil
	}

	failedList := make([]string, 0, len(failedModels))
	for m := range failedModels {
		failedList = append(failedList, m)
	}

	return nil, fmt.Errorf("all models failed (tried: %v): %w", failedList, lastErr)
}

// GetModelStats returns model usage statistics.
func (r *Router) GetModelStats() map[string]int {
	return r.selector.Stats()
}

// GetAvailableModels returns the list of configured models.
func (r *Router) GetAvailableModels() []string {
	return r.selector.GetModels()
}

// MockClient is a test/development LLM client.
type MockClient struct {
	Provider string
	Model    string
}

// Generate returns a mock response for testing.
func (c MockClient) Generate(systemPrompt, userPrompt string) (string, error) {
	if strings.TrimSpace(userPrompt) == "" {
		return "", errors.New("user prompt is required")
	}
	return fmt.Sprintf("%s\n\n%s\n\nGenerated by the Go %s provider using model %s.", systemPrompt, userPrompt, c.Provider, c.Model), nil
}
